(() => {
  'use strict';
  const current = document.body.dataset.page || 'home';
  const item = (page, href, label) => `<a data-page="${page}" ${current===page?'class="active" aria-current="page"':''} href="${href}">${label}</a>`;
  const items = [
    ['home','/es/','Inicio'],['about','/es/about','Nosotros'],['services','/es/services','Servicios'],['prices','/es/prices','Precios'],['subscriptions','/es/subscriptions','Planes Web'],['templates','/es/templates','Plantillas'],['portfolio','/es/portfolio','Portafolio'],['reviews','/es/reviews','Reseñas'],['contact','/es/contact','Contacto'],['login','/es/login','Ingresar']
  ];
  const links = items.map(([page,href,label])=>item(page,href,label)).join('');
  const brand = `<span class="brand-text"><strong>BAM'S</strong><small>WEBSITE BUILDER</small></span>`;
  document.body.insertAdjacentHTML('afterbegin', `<header class="site-header" id="site-header"><div class="header-container"><a class="site-brand" href="/es/" aria-label="Inicio de BAM's Website Builder">${brand}</a><nav class="desktop-navigation" aria-label="Navegación principal">${links}</nav><div class="desktop-language"><a href="/${current==='home'?'':current}">English</a><span>|</span><a class="language-active" href="/es/${current==='home'?'':current}">Español</a></div><button class="menu-toggle" id="menu-toggle" type="button" aria-label="Abrir menú" aria-controls="mobile-menu" aria-expanded="false"><span></span><span></span><span></span></button></div></header><div class="menu-overlay" id="menu-overlay"></div><aside class="mobile-menu" id="mobile-menu" aria-hidden="true" aria-label="Navegación móvil"><div class="mobile-menu-header"><a class="mobile-menu-brand" href="/es/">${brand}</a><button class="mobile-menu-close" id="mobile-menu-close" type="button" aria-label="Cerrar menú"><span></span><span></span></button></div><nav class="mobile-navigation">${links}</nav><div class="mobile-language-section"><p>Idioma</p><div class="mobile-language-links"><a href="/${current==='home'?'':current}">English</a><a class="language-active" href="/es/${current==='home'?'':current}">Español</a></div></div><div class="mobile-menu-cta"><a href="/es/contact">Solicita una cotización</a></div></aside>`);
  document.body.insertAdjacentHTML('beforeend', `<footer class="home-footer"><div class="footer-grid"><div><h3>BAM'S WEBSITE BUILDER</h3><p>Sitios web profesionales y adaptables creados para fortalecer la presencia de pequeñas empresas.</p></div><div><h4>Enlaces</h4><div class="footer-links"><a href="/es/about">Nosotros</a><a href="/es/services">Servicios</a><a href="/es/prices">Precios</a><a href="/es/templates">Plantillas</a><a href="/es/portfolio">Portafolio</a><a href="/es/reviews">Reseñas</a></div></div><div><h4>Clientes</h4><div class="footer-links"><a href="/es/login">Ingresar</a><a href="/es/register">Crear cuenta</a><a href="/es/forgot-password">Recuperar contraseña</a></div></div><div><h4>Contacto</h4><div class="footer-links"><a href="tel:+17274178762">727-417-8762</a><a href="mailto:bamswebsitebuilder@gmail.com">bamswebsitebuilder@gmail.com</a><a href="/es/contact">Solicitar cotización</a></div></div></div><div class="footer-bottom">© 2026 BAM's Website Builder. Todos los derechos reservados.</div></footer>`);
})();
